INSERT IGNORE INTO categories (name) VALUES
    ('Hrana'),
    ('Zivotinje'),
    ('Predmeti'),
    ('Mesta');

INSERT IGNORE INTO word_entries (category_id, value, active) VALUES
    ((SELECT id FROM categories WHERE name = 'Hrana'), 'Pizza', TRUE),
    ((SELECT id FROM categories WHERE name = 'Hrana'), 'Banana', TRUE),
    ((SELECT id FROM categories WHERE name = 'Hrana'), 'Palacinke', TRUE),
    ((SELECT id FROM categories WHERE name = 'Hrana'), 'Kokice', TRUE),
    ((SELECT id FROM categories WHERE name = 'Hrana'), 'Lubenica', TRUE),
    ((SELECT id FROM categories WHERE name = 'Hrana'), 'Supa', TRUE),
    ((SELECT id FROM categories WHERE name = 'Zivotinje'), 'Pingvin', TRUE),
    ((SELECT id FROM categories WHERE name = 'Zivotinje'), 'Delfin', TRUE),
    ((SELECT id FROM categories WHERE name = 'Zivotinje'), 'Slon', TRUE),
    ((SELECT id FROM categories WHERE name = 'Zivotinje'), 'Pauk', TRUE),
    ((SELECT id FROM categories WHERE name = 'Zivotinje'), 'Papagaj', TRUE),
    ((SELECT id FROM categories WHERE name = 'Zivotinje'), 'Kengur', TRUE),
    ((SELECT id FROM categories WHERE name = 'Predmeti'), 'Kisobran', TRUE),
    ((SELECT id FROM categories WHERE name = 'Predmeti'), 'Ogledalo', TRUE),
    ((SELECT id FROM categories WHERE name = 'Predmeti'), 'Gitara', TRUE),
    ((SELECT id FROM categories WHERE name = 'Predmeti'), 'Sat', TRUE),
    ((SELECT id FROM categories WHERE name = 'Predmeti'), 'Kofer', TRUE),
    ((SELECT id FROM categories WHERE name = 'Predmeti'), 'Sveca', TRUE),
    ((SELECT id FROM categories WHERE name = 'Mesta'), 'Aerodrom', TRUE),
    ((SELECT id FROM categories WHERE name = 'Mesta'), 'Biblioteka', TRUE),
    ((SELECT id FROM categories WHERE name = 'Mesta'), 'Plaza', TRUE),
    ((SELECT id FROM categories WHERE name = 'Mesta'), 'Bolnica', TRUE),
    ((SELECT id FROM categories WHERE name = 'Mesta'), 'Muzej', TRUE),
    ((SELECT id FROM categories WHERE name = 'Mesta'), 'Stadion', TRUE);

INSERT IGNORE INTO associations (word_entry_id, value) VALUES
    ((SELECT id FROM word_entries WHERE value = 'Pizza'), 'Italija'),
    ((SELECT id FROM word_entries WHERE value = 'Pizza'), 'Trougao'),
    ((SELECT id FROM word_entries WHERE value = 'Banana'), 'Zuto'),
    ((SELECT id FROM word_entries WHERE value = 'Banana'), 'Majmun'),
    ((SELECT id FROM word_entries WHERE value = 'Palacinke'), 'Tiganj'),
    ((SELECT id FROM word_entries WHERE value = 'Palacinke'), 'Krem'),
    ((SELECT id FROM word_entries WHERE value = 'Kokice'), 'Bioskop'),
    ((SELECT id FROM word_entries WHERE value = 'Kokice'), 'Kukuruz'),
    ((SELECT id FROM word_entries WHERE value = 'Lubenica'), 'Leto'),
    ((SELECT id FROM word_entries WHERE value = 'Lubenica'), 'Kora'),
    ((SELECT id FROM word_entries WHERE value = 'Supa'), 'Kasika'),
    ((SELECT id FROM word_entries WHERE value = 'Supa'), 'Toplo'),
    ((SELECT id FROM word_entries WHERE value = 'Pingvin'), 'Led'),
    ((SELECT id FROM word_entries WHERE value = 'Pingvin'), 'Frak'),
    ((SELECT id FROM word_entries WHERE value = 'Delfin'), 'More'),
    ((SELECT id FROM word_entries WHERE value = 'Delfin'), 'Skok'),
    ((SELECT id FROM word_entries WHERE value = 'Slon'), 'Surla'),
    ((SELECT id FROM word_entries WHERE value = 'Slon'), 'Veliko'),
    ((SELECT id FROM word_entries WHERE value = 'Pauk'), 'Mreza'),
    ((SELECT id FROM word_entries WHERE value = 'Pauk'), 'Osam'),
    ((SELECT id FROM word_entries WHERE value = 'Papagaj'), 'Govor'),
    ((SELECT id FROM word_entries WHERE value = 'Papagaj'), 'Sareno'),
    ((SELECT id FROM word_entries WHERE value = 'Kengur'), 'Dzep'),
    ((SELECT id FROM word_entries WHERE value = 'Kengur'), 'Australija'),
    ((SELECT id FROM word_entries WHERE value = 'Kisobran'), 'Kisa'),
    ((SELECT id FROM word_entries WHERE value = 'Kisobran'), 'Sklapanje'),
    ((SELECT id FROM word_entries WHERE value = 'Ogledalo'), 'Odraz'),
    ((SELECT id FROM word_entries WHERE value = 'Ogledalo'), 'Kupatilo'),
    ((SELECT id FROM word_entries WHERE value = 'Gitara'), 'Zice'),
    ((SELECT id FROM word_entries WHERE value = 'Gitara'), 'Muzika'),
    ((SELECT id FROM word_entries WHERE value = 'Sat'), 'Vreme'),
    ((SELECT id FROM word_entries WHERE value = 'Sat'), 'Kazaljke'),
    ((SELECT id FROM word_entries WHERE value = 'Kofer'), 'Putovanje'),
    ((SELECT id FROM word_entries WHERE value = 'Kofer'), 'Prtljag'),
    ((SELECT id FROM word_entries WHERE value = 'Sveca'), 'Plamen'),
    ((SELECT id FROM word_entries WHERE value = 'Sveca'), 'Vosak'),
    ((SELECT id FROM word_entries WHERE value = 'Aerodrom'), 'Avion'),
    ((SELECT id FROM word_entries WHERE value = 'Aerodrom'), 'Pasos'),
    ((SELECT id FROM word_entries WHERE value = 'Biblioteka'), 'Tisina'),
    ((SELECT id FROM word_entries WHERE value = 'Biblioteka'), 'Knjige'),
    ((SELECT id FROM word_entries WHERE value = 'Plaza'), 'Pesak'),
    ((SELECT id FROM word_entries WHERE value = 'Plaza'), 'More'),
    ((SELECT id FROM word_entries WHERE value = 'Bolnica'), 'Doktor'),
    ((SELECT id FROM word_entries WHERE value = 'Bolnica'), 'Hodnik'),
    ((SELECT id FROM word_entries WHERE value = 'Muzej'), 'Izlozba'),
    ((SELECT id FROM word_entries WHERE value = 'Muzej'), 'Istorija'),
    ((SELECT id FROM word_entries WHERE value = 'Stadion'), 'Navijaci'),
    ((SELECT id FROM word_entries WHERE value = 'Stadion'), 'Tribine');
